/* eslint-disable @typescript-eslint/naming-convention, sort-keys */
import { error, off, warn } from './error-levels'
import paddingLineBetweenStatements from './padding-lines-between-statements'

const commonRules = {
  // Possible Problems
  'array-callback-return'           : error,
  'no-await-in-loop'                : error,
  'no-constant-binary-expression'   : error,
  'no-constructor-return'           : error,
  'no-duplicate-imports'            : error,
  'no-fallthrough'                  : error,
  'no-new-native-nonconstructor'    : error,
  'no-promise-executor-return'      : error,
  'no-self-compare'                 : error,
  'no-unmodified-loop-condition'    : error,
  'no-unreachable-loop'             : error,
  'no-unused-private-class-members' : error,
  'no-use-before-define'            : error,
  'require-atomic-updates'          : error,

  // Suggestions
  'accessor-pairs'         : error,
  'arrow-body-style'       : error,
  'block-scoped-var'       : error,
  camelcase                : error,
  'class-methods-use-this' : error,
  complexity               : [ error, 15 ],
  curly                    : error,
  'default-case-last'      : error,
  'default-param-last'     : error,
  'dot-notation'           : error,
  eqeqeq                   : error,
  'func-style'             : [ error ],
  'grouped-accessor-pairs' : [ error, 'getBeforeSet' ],
  'id-length'              : [
    error,
    {
      exceptions : [ 'id', 'on', 't', 'to', '_' ],
      min        : 2,
    },
  ],

  '@stylistic/no-confusing-arrow' : error,
  '@stylistic/no-mixed-operators' : error,
  'max-classes-per-file'          : error,
  'max-depth'                     : [ error, 3 ],
  'max-lines'                     : [ error, 1000 ],
  'max-nested-callbacks'          : [ error, 3 ],
  'max-params'                    : error,
  'new-cap'                       : error,
  'no-alert'                      : error,
  'no-array-constructor'          : error,
  'no-console'                    : warn,
  'no-else-return'                : error,
  'no-empty-function'             : error,
  'no-empty-static-block'         : error,
  'no-eval'                       : warn,
  'no-implicit-globals'           : error,
  'no-implied-eval'               : warn,
  'no-invalid-this'               : error,
  'no-iterator'                   : error,
  'no-labels'                     : error,
  'no-lone-blocks'                : error,
  'no-loop-func'                  : error,
  'no-multi-assign'               : error,
  'no-negated-condition'          : warn,
  'no-nested-ternary'             : error,
  'no-new'                        : error,
  'no-new-func'                   : error,
  'no-new-wrappers'               : error,
  'no-param-reassign'             : error,
  'no-proto'                      : error,
  'no-return-assign'              : error,
  'no-script-url'                 : error,
  'no-sequences'                  : error,
  'no-shadow'                     : error,
  'no-throw-literal'              : error,
  'no-unneeded-ternary'           : error,
  'no-unused-expressions'         : error,
  'no-useless-call'               : error,
  'no-useless-computed-key'       : error,
  'no-useless-concat'             : error,
  'no-useless-constructor'        : error,
  'no-useless-rename'             : error,
  'no-useless-return'             : error,
  'no-var'                        : error,
  'no-void'                       : error,
  'object-shorthand'              : error,
  'operator-assignment'           : error,
  'prefer-arrow-callback'         : error,
  'prefer-const'                  : error,
  'prefer-destructuring'          : error,
  'prefer-object-spread'          : error,
  'prefer-promise-reject-errors'  : error,
  'prefer-rest-params'            : error,
  'prefer-spread'                 : error,
  'prefer-template'               : error,
  'require-await'                 : error,
  'sort-keys'                     : [
    error,
    'asc',
    {
      allowLineSeparatedGroups : true,
      caseSensitive            : false,
      natural                  : true,
    },
  ],
  yoda : [ error, 'always' ],

  // Layout & Formatting
  '@stylistic/array-bracket-newline'          : [ error, { multiline: true } ],
  '@stylistic/array-bracket-spacing'          : [ error, 'always' ],
  '@stylistic/array-element-newline'          : [ error, 'consistent' ],
  '@stylistic/arrow-parens'                   : [ error, 'always' ],
  '@stylistic/arrow-spacing'                  : error,
  '@stylistic/block-spacing'                  : error,
  '@stylistic/brace-style'                    : [ error, '1tbs', { allowSingleLine: false } ],
  '@stylistic/comma-dangle'                   : [ error, 'always-multiline' ],
  '@stylistic/comma-spacing'                  : error,
  '@stylistic/comma-style'                    : [ error, 'last' ],
  '@stylistic/computed-property-spacing'      : [ error, 'never' ],
  '@stylistic/dot-location'                   : [ error, 'property' ],
  '@stylistic/eol-last'                       : error,
  '@stylistic/function-call-spacing'          : error,
  '@stylistic/function-call-argument-newline' : [ error, 'consistent' ],
  '@stylistic/function-paren-newline'         : [ error, 'consistent' ],
  '@stylistic/generator-star-spacing'         : [ error, 'before' ],
  '@stylistic/implicit-arrow-linebreak'       : error,
  '@stylistic/indent'                         : [ error, 2, { SwitchCase: 1 } ],
  '@stylistic/jsx-quotes'                     : [ error, 'prefer-single' ],
  '@stylistic/key-spacing'                    : [
    error,
    {
      multiLine : {
        afterColon  : true,
        align       : 'colon',
        beforeColon : true,
      },
      singleLine : {
        afterColon  : true,
        beforeColon : false,
      },
    },
  ],
  '@stylistic/keyword-spacing'             : error,
  '@stylistic/linebreak-style'             : error,
  '@stylistic/lines-between-class-members' : [ error, 'always' ],
  '@stylistic/max-statements-per-line'     : error,
  '@stylistic/multiline-ternary'           : [ error, 'always-multiline' ],
  '@stylistic/new-parens'                  : error,
  '@stylistic/newline-per-chained-call'    : [ error, { ignoreChainWithDepth: 1 } ],
  '@stylistic/no-extra-parens'             : [
    'error',
    'all',
    {
      conditionalAssign       : false,
      ignoreJSX               : 'all',
      nestedBinaryExpressions : false,
      returnAssign            : false,
      ignoredNodes            : [ 'ConditionalExpression' ],
    },
  ],
  '@stylistic/no-multi-spaces' : [
    error,
    { exceptions: { TSPropertySignature: true } },
  ],
  '@stylistic/no-multiple-empty-lines'       : [ error, { max: 1 } ],
  '@stylistic/no-new-symbol'                 : off,
  '@stylistic/no-tabs'                       : error,
  '@stylistic/no-trailing-spaces'            : error,
  '@stylistic/no-whitespace-before-property' : error,
  '@stylistic/object-curly-newline'          : [ error, { multiline: true } ],
  '@stylistic/object-curly-spacing'          : [ error, 'always' ],
  '@stylistic/object-property-newline'       : error,
  '@stylistic/operator-linebreak'            : [
    error,
    'none',
    {
      overrides : {
        ':' : 'before',
        '?' : 'before',

        '&&' : 'before',
        '||' : 'before',
      },
    },
  ],
  '@stylistic/padded-blocks'                   : [ error, 'never' ],
  '@stylistic/padding-line-between-statements' : [
    error,
    ...paddingLineBetweenStatements,
  ],
  '@stylistic/quotes'                      : [ error, 'single' ],
  '@stylistic/rest-spread-spacing'         : error,
  '@stylistic/semi'                        : [ error, 'never' ],
  '@stylistic/semi-spacing'                : error,
  '@stylistic/semi-style'                  : error,
  '@stylistic/space-before-blocks'         : error,
  '@stylistic/space-before-function-paren' : [
    error,
    {
      anonymous  : 'never',
      asyncArrow : 'always',
      named      : 'never',
    },
  ],
  '@stylistic/space-in-parens' : [ error, 'always' ],
  '@stylistic/space-infix-ops' : error,
  '@stylistic/space-unary-ops' : [
    error,
    {
      nonwords : false,
      words    : true,
    },
  ],
  '@stylistic/switch-colon-spacing'   : error,
  '@stylistic/template-curly-spacing' : [ error, 'always' ],
  '@stylistic/template-tag-spacing'   : error,
  '@stylistic/wrap-iife'              : error,
  '@stylistic/wrap-regex'             : error,
  '@stylistic/yield-star-spacing'     : error,
}

export default commonRules
